language: python
python:
  - "2.7"
before_install:
  - "sudo apt-get install python-dev"
  - ./download_etcd.sh 2.3.7
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov codecov
before_script:
  - nohup ./bin/etcd &
script:
  - pytest --cov=./
after_success:
  - codecov